
all:
	gcc -o popen1        popen1.c
	gcc -o popen2        popen2.c
	gcc -o popen3        popen3.c
	gcc -o popen4        popen4.c
	gcc -o pipe1         pipe1.c
	gcc -o pipe2_fork    pipe2_fork.c
	gcc -o pipe3_exec_data_producer    pipe3_exec_data_producer.c
	gcc -o pipe4_exec_data_consumer    pipe4_exec_data_consumer.c
	gcc -o pipe5_dup     pipe5_dup.c
	gcc -o fifo1         fifo1.c
	gcc -o fifo2         fifo2.c
	gcc -o fifo3_producer              fifo3_producer.c
	gcc -o fifo4_consumer              fifo4_consumer.c
	gcc -o server        server.c
	gcc -o client        client.c

clean:
	rm -rf popen1 popen2 popen3 popen4 pipe1 pipe2_fork pipe3_exec_data_producer \
        pipe4_exec_data_consumer pipe5_dup fifo1 fifo2 fifo3_producer fifo4_consumer \
        server client
