
all:
	gcc -o popen1   popen1.c
	gcc -o popen2   popen2.c
	gcc -o popen3   popen3.c
	gcc -o popen4   popen4.c
	gcc -o pipe1    pipe1.c
	gcc -o pipe2    pipe2.c
	gcc -o pipe3    pipe3.c
	gcc -o pipe4    pipe4.c
	gcc -o pipe5    pipe5.c

clean:
	rm -rf popen1 popen2 popen3 popen4 pipe1 pipe2 pipe3 pipe4 pipe5
