
all:  
	gcc -o client1      client1.c
	gcc -o server1      server1.c
	gcc -o client2      client2.c
	gcc -o server2      server2.c
	gcc -o client3      client3.c
	gcc -o server3      server3.c
	gcc -o getname      getname.c
	gcc -o getdate      getdate.c
	gcc -o server4      server4.c
	gcc -o select       select.c

clean:
	rm -rf client1 server1 server_socket client2 server2 getname getdate \
        client3 server3 server4 select
